[project]
name = "cfcache"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.40.36",
    "duckdb>=1.4.1",
    "imbalanced-learn>=0.14.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "onnxruntime>=1.23.2",
    "pandas>=2.3.3",
    "regex>=2025.11.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "skl2onnx>=1.19.1",
    "zstandard>=0.22.0",
]
